let misi = {
	"macan" : {
		"1" : "lakukanlah jalan nobita 2 kali pengulangan,https://drive.google.com/file/d/13jdrGEfrrTuzwN5LXVMKYe6V2jYbm4_o/view?usp=drive_link",
		"3" : "lakukanlah lari ala naruto 2 kali pengulangan,https://drive.google.com/file/d/13unWOFHy2pmF7GkkPcsXsc-pdJlwsLPx/view?usp=drive_link",
		"5" : "lakukanlah lompat Boots,https://drive.google.com/file/d/104nyRlJpKxHywfQNkbYewWaclVYvIWPj/view?usp=drive_link",
		"6" : "lakukanlah loncat red kangoroo,https://drive.google.com/file/d/14EBlKp6B60ao2U3RIyWy8BDCWlju93ZT/view?usp=drive_link",
		"7" : "lakukanlah jalan hulk 2 kali pengulangan,https://drive.google.com/file/d/13Y0xiJYs4GFwzwc47WaDTAkIVThj68eS/view?usp=drive_link",
		"8" : "lakukanlah lari captain tsubatsa 2 kali pengulangan,https://drive.google.com/file/d/1-xLif57pHpDyX0yLYV_SsOLf0LiipTS7/view?usp=drive_link",
		"10" : "lakukanlah lompat crazy frog,https://drive.google.com/file/d/105j3G3S7NbGYCK-IXUDAhqo4tysOXGhW/view?usp=drive_link",
		"12" : "lakukanlah jalan tuan crab 2 kali pengulangan,https://drive.google.com/file/d/13XoZm7nOWDCNWRoQssp2DSK_4_5P9-AX/view?usp=drive_link",
		"13" : "lakukanlah loncat marsupilami,https://drive.google.com/file/d/14HcSVQu6aVgATKy3nVl17BHeHphjAb7L/view?usp=drive_link", //
		"15" : "lakukanlah lari swepper 2 kali pengulangan,https://drive.google.com/file/d/1048ayR5Co_WtnqIqLnZJsy3rxDXBb83Z/view?usp=drive_link", 
		"17" : "lakukanlah lompat ninja hatori,https://drive.google.com/file/d/13yjWf8cZXrbt4C8XWLHRKCOzVZUujRet/view?usp=drive_link", 
		"19" : "lakukanlah loncat shincan,https://drive.google.com/file/d/14Kw37WbXHwyuD41yFtLF7cN0oa_vG-KY/view?usp=drive_link", 
		"20" : "lakukanlah jalan oscar menekan tombol 2 kali pengulangan,https://drive.google.com/file/d/13VME8R-nDBEAk-IFOVZjOyAJXztVYZHD/view?usp=drive_link", 
		"21" : "lakukanlah lari son go han 2 kali pengulangan,https://drive.google.com/file/d/10-dUOETbsSt5mc3vc2F9dnwW3yXTmsL8/view?usp=drive_link", 
		"23" : "lakukanlah lompat ultraman,https://drive.google.com/file/d/14ClO4yI84JRCVyhNwH3LlepzEEpiKbeT/view?usp=drive_link", 
		"24" : "lakukanlah loncat donald bebek,https://drive.google.com/file/d/14Kg1uG-Yt5ZGOG_ikvcQC4i5JuoMsx2E/view?usp=drive_link", 
	},
	"bebek" : {
		"2" : "lakukanlah jalan nobita 2 kali pengulangan,https://drive.google.com/file/d/13jdrGEfrrTuzwN5LXVMKYe6V2jYbm4_o/view?usp=drive_link",
		"3" : "lakukanlah lari ala naruto 2 kali pengulangan,https://drive.google.com/file/d/13unWOFHy2pmF7GkkPcsXsc-pdJlwsLPx/view?usp=drive_link",
		"5" : "lakukanlah lompat boots,https://drive.google.com/file/d/104nyRlJpKxHywfQNkbYewWaclVYvIWPj/view?usp=drive_link",
		"6" : "lakukanlah loncat red kangoroo,https://drive.google.com/file/d/14EBlKp6B60ao2U3RIyWy8BDCWlju93ZT/view?usp=drive_link",
		"7" : "lakukanlah jalan hulk 2 kali pengulangan,https://drive.google.com/file/d/13Y0xiJYs4GFwzwc47WaDTAkIVThj68eS/view?usp=drive_link",
		"8" : "lakukanlah lari captain tsubatsa 2 kali pengulangan,https://drive.google.com/file/d/1-xLif57pHpDyX0yLYV_SsOLf0LiipTS7/view?usp=drive_link",
		"10" : "lakukanlah lompat crazy frog,https://drive.google.com/file/d/105j3G3S7NbGYCK-IXUDAhqo4tysOXGhW/view?usp=drive_link",
		"11" : "lakukanlah loncat marsupilami,https://drive.google.com/file/d/14HcSVQu6aVgATKy3nVl17BHeHphjAb7L/view?usp=drive_link",
		"12" : "lakukanlah jalan tuan crab 2 kali pengulangan,https://drive.google.com/file/d/13XoZm7nOWDCNWRoQssp2DSK_4_5P9-AX/view?usp=drive_link",
		"14" : "lakukanlah lari son go han 2 kali pengulangan,https://drive.google.com/file/d/10-dUOETbsSt5mc3vc2F9dnwW3yXTmsL8/view?usp=drive_link", 
		"15" : "lakukanlah lompat ninja hatori,https://drive.google.com/file/d/13yjWf8cZXrbt4C8XWLHRKCOzVZUujRet/view?usp=drive_link",
		"17" : "lakukanlah loncat shincan,https://drive.google.com/file/d/14Kw37WbXHwyuD41yFtLF7cN0oa_vG-KY/view?usp=drive_link", 
		"19" : "lakukanlah loncat marsupilami,https://drive.google.com/file/d/14HcSVQu6aVgATKy3nVl17BHeHphjAb7L/view?usp=drive_link", 
		"20" : "lakukanlah jalan oscar menekan tombol 2 kali pengulangan,https://drive.google.com/file/d/13VME8R-nDBEAk-IFOVZjOyAJXztVYZHD/view?usp=drive_link", 
		"21" : "lakukanlah lari swepper 2 kali pengulangan,https://drive.google.com/file/d/1048ayR5Co_WtnqIqLnZJsy3rxDXBb83Z/view?usp=drive_link", 
		"22" : "lakukanlah lompat ultraman,https://drive.google.com/file/d/14ClO4yI84JRCVyhNwH3LlepzEEpiKbeT/view?usp=drive_link",
		"23" : "lakukanlah loncat donald bebek,https://drive.google.com/file/d/14Kg1uG-Yt5ZGOG_ikvcQC4i5JuoMsx2E/view?usp=drive_link",
	},
	"gajah" : {
		"1" : "lakukanlah lari ala naruto 2 kali pengulangan,https://drive.google.com/file/d/13unWOFHy2pmF7GkkPcsXsc-pdJlwsLPx/view?usp=drive_link",
		"2" : "lakukanlah jalan nobita 2 kali pengulangan,https://drive.google.com/file/d/13jdrGEfrrTuzwN5LXVMKYe6V2jYbm4_o/view?usp=drive_link",
		"4" : "lakukanlah lompat boots,https://drive.google.com/file/d/104nyRlJpKxHywfQNkbYewWaclVYvIWPj/view?usp=drive_link",
		"6" : "lakukanlah loncat red kangoroo,https://drive.google.com/file/d/14EBlKp6B60ao2U3RIyWy8BDCWlju93ZT/view?usp=drive_link",
		"7" : "lakukanlah jalan hulk 2 kali pengulangan,https://drive.google.com/file/d/13Y0xiJYs4GFwzwc47WaDTAkIVThj68eS/view?usp=drive_link",
		"9" : "lakukanlah lari captain tsubatsa 2 kali pengulangan,https://drive.google.com/file/d/1-xLif57pHpDyX0yLYV_SsOLf0LiipTS7/view?usp=drive_link",
		"10" : "lakukanlah lompat crazy frog,https://drive.google.com/file/d/105j3G3S7NbGYCK-IXUDAhqo4tysOXGhW/view?usp=drive_link",
		"13" : "lakukanlah loncat marsupilami,https://drive.google.com/file/d/14HcSVQu6aVgATKy3nVl17BHeHphjAb7L/view?usp=drive_link",
		"14" : "lakukanlah jalan tuan crab 2 kali pengulangan,https://drive.google.com/file/d/13XoZm7nOWDCNWRoQssp2DSK_4_5P9-AX/view?usp=drive_link",
		"15" : "lakukanlah lari son go han 2 kali pengulangan,https://drive.google.com/file/d/10-dUOETbsSt5mc3vc2F9dnwW3yXTmsL8/view?usp=drive_link", 
		"19" : "lakukanlah loncat shincan,https://drive.google.com/file/d/14Kw37WbXHwyuD41yFtLF7cN0oa_vG-KY/view?usp=drive_link", 
		"20" : "lakukanlah jalan oscar menekan tombol 2 kali pengulangan,https://drive.google.com/file/d/13VME8R-nDBEAk-IFOVZjOyAJXztVYZHD/view?usp=drive_link", 
		"21" : "lakukanlah lari swepper 2 kali pengulangan,https://drive.google.com/file/d/1048ayR5Co_WtnqIqLnZJsy3rxDXBb83Z/view?usp=drive_link", 
		"23" : "lakukanlah lompat ultraman,https://drive.google.com/file/d/14ClO4yI84JRCVyhNwH3LlepzEEpiKbeT/view?usp=drive_link",
		"24" : "lakukanlah loncat donald bebek,https://drive.google.com/file/d/14Kg1uG-Yt5ZGOG_ikvcQC4i5JuoMsx2E/view?usp=drive_link",
	},
	"kerbau" : {
		"1" : "lakukanlah jalan tuan crab 2 kali pengulangan,https://drive.google.com/file/d/13XoZm7nOWDCNWRoQssp2DSK_4_5P9-AX/view?usp=drive_link",	
		"2" : "lakukanlah jalan oscar menekan tombol 2 kali pengulangan,https://drive.google.com/file/d/13VME8R-nDBEAk-IFOVZjOyAJXztVYZHD/view?usp=drive_link", 	
		"3" : "lakukanlah lari ala naruto 2 kali pengulangan,https://drive.google.com/file/d/13unWOFHy2pmF7GkkPcsXsc-pdJlwsLPx/view?usp=drive_link",
		"5" : "lakukanlah jalan nobita 2 kali pengulangan,https://drive.google.com/file/d/13jdrGEfrrTuzwN5LXVMKYe6V2jYbm4_o/view?usp=drive_link",
		"7" : "lakukanlah lari segitiga sebanyak 2 kali pengulangan,https://drive.google.com/file/d/1-xLif57pHpDyX0yLYV_SsOLf0LiipTS7/view?usp=drive_link",
		"8" : "lakukanlah lari son go han 2 kali pengulangan,https://drive.google.com/file/d/10-dUOETbsSt5mc3vc2F9dnwW3yXTmsL8/view?usp=drive_link", 
		"9" : "lakukanlah lari swepper 2 kali pengulangan,https://drive.google.com/file/d/1048ayR5Co_WtnqIqLnZJsy3rxDXBb83Z/view?usp=drive_link", 
		"10" : "lakukanlah lompat ninja hatori,https://drive.google.com/file/d/13yjWf8cZXrbt4C8XWLHRKCOzVZUujRet/view?usp=drive_link", 
		"12" : "lakukanlah jalan hulk 2 kali pengulangan,https://drive.google.com/file/d/13Y0xiJYs4GFwzwc47WaDTAkIVThj68eS/view?usp=drive_link",
		"15" : "lakukanlah lompat boots,https://drive.google.com/file/d/104nyRlJpKxHywfQNkbYewWaclVYvIWPj/view?usp=drive_link",
		"18" : "lakukanlah lompat ultraman,https://drive.google.com/file/d/14ClO4yI84JRCVyhNwH3LlepzEEpiKbeT/view?usp=drive_link",
		"19" : "lakukanlah loncat marsupilami,https://drive.google.com/file/d/14HcSVQu6aVgATKy3nVl17BHeHphjAb7L/view?usp=drive_link",
		"20" : "lakukanlah loncat red kangoroo,https://drive.google.com/file/d/14EBlKp6B60ao2U3RIyWy8BDCWlju93ZT/view?usp=drive_link",
		"21" : "lakukanlah loncat donald bebek,https://drive.google.com/file/d/14Kg1uG-Yt5ZGOG_ikvcQC4i5JuoMsx2E/view?usp=drive_link",
		"22" : "lakukanlah loncat marsupilami,https://drive.google.com/file/d/14HcSVQu6aVgATKy3nVl17BHeHphjAb7L/view?usp=drive_link",
		"23" : "lakukanlah loncat shincan,https://drive.google.com/file/d/14Kw37WbXHwyuD41yFtLF7cN0oa_vG-KY/view?usp=drive_link", 
		"24" : "lakukanlah lompat crazy frog,https://drive.google.com/file/d/105j3G3S7NbGYCK-IXUDAhqo4tysOXGhW/view?usp=drive_link",


	},
}