let misi = {
	"macan" : {
		"1" : "Lakukanlah Jalan Nobita 2 kali pengulangan,https://drive.google.com/file/d/13jdrGEfrrTuzwN5LXVMKYe6V2jYbm4_o/view?usp=drive_link",
		"3" : "Lakukanlah Lari Ala Naruto 2 kali pengulangan,https://drive.google.com/file/d/13unWOFHy2pmF7GkkPcsXsc-pdJlwsLPx/view?usp=drive_link",
		"5" : "Lakukanlah Lompat Boots,https://drive.google.com/file/d/104nyRlJpKxHywfQNkbYewWaclVYvIWPj/view?usp=drive_link",
		"6" : "Lakukanlah Loncat Red Kangoroo,https://drive.google.com/file/d/14EBlKp6B60ao2U3RIyWy8BDCWlju93ZT/view?usp=drive_link",
		"7" : "Lakukanlah Jalan Hulk 2 kali pengulangan,https://drive.google.com/file/d/13Y0xiJYs4GFwzwc47WaDTAkIVThj68eS/view?usp=drive_link",
		"8" : "Lakukanlah Lari Captain Tsubatsa 2 kali pengulangan,https://drive.google.com/file/d/1-xLif57pHpDyX0yLYV_SsOLf0LiipTS7/view?usp=drive_link",
		"10" : "Lakukanlah Lompat Crazy Frog,https://drive.google.com/file/d/105j3G3S7NbGYCK-IXUDAhqo4tysOXGhW/view?usp=drive_link",
		"12" : "Lakukanlah Jalan Tuan Crab 2 kali pengulangan,https://drive.google.com/file/d/13XoZm7nOWDCNWRoQssp2DSK_4_5P9-AX/view?usp=drive_link",
		"13" : "Lakukanlah Loncat Marsupilami,https://drive.google.com/file/d/14HcSVQu6aVgATKy3nVl17BHeHphjAb7L/view?usp=drive_link", //
		"15" : "Lakukanlah Lari Swepper 2 kali pengulangan,https://drive.google.com/file/d/1048ayR5Co_WtnqIqLnZJsy3rxDXBb83Z/view?usp=drive_link", 
		"17" : "Lakukanlah Lompat Ninja Hatori,https://drive.google.com/file/d/13yjWf8cZXrbt4C8XWLHRKCOzVZUujRet/view?usp=drive_link", 
		"19" : "Lakukanlah Loncat Shincan,https://drive.google.com/file/d/14Kw37WbXHwyuD41yFtLF7cN0oa_vG-KY/view?usp=drive_link", 
		"20" : "Lakukanlah jalan Oscar Menekan Tombol 2 kali pengulangan,https://drive.google.com/file/d/13VME8R-nDBEAk-IFOVZjOyAJXztVYZHD/view?usp=drive_link", 
		"21" : "Lakukanlah Lari Son Go Han 2 kali pengulangan,https://drive.google.com/file/d/10-dUOETbsSt5mc3vc2F9dnwW3yXTmsL8/view?usp=drive_link", 
		"23" : "Lakukanlah Lompat Ultraman,https://drive.google.com/file/d/14ClO4yI84JRCVyhNwH3LlepzEEpiKbeT/view?usp=drive_link", 
		"24" : "Lakukanlah Loncat Donald Duck,https://drive.google.com/file/d/14Kg1uG-Yt5ZGOG_ikvcQC4i5JuoMsx2E/view?usp=drive_link", 
	},
	"bebek" : {
		"2" : "Lakukanlah Jalan Nobita 2 kali pengulangan,https://drive.google.com/file/d/13jdrGEfrrTuzwN5LXVMKYe6V2jYbm4_o/view?usp=drive_link",
		"3" : "Lakukanlah Lari Ala Naruto 2 kali pengulangan,https://drive.google.com/file/d/13unWOFHy2pmF7GkkPcsXsc-pdJlwsLPx/view?usp=drive_link",
		"5" : "Lakukanlah Lompat Boots,https://drive.google.com/file/d/104nyRlJpKxHywfQNkbYewWaclVYvIWPj/view?usp=drive_link",
		"6" : "Lakukanlah Loncat Red Kangoroo,https://drive.google.com/file/d/14EBlKp6B60ao2U3RIyWy8BDCWlju93ZT/view?usp=drive_link",
		"7" : "Lakukanlah Jalan Hulk 2 kali pengulangan,https://drive.google.com/file/d/13Y0xiJYs4GFwzwc47WaDTAkIVThj68eS/view?usp=drive_link",
		"8" : "Lakukanlah Lari Captain Tsubatsa 2 kali pengulangan,https://drive.google.com/file/d/1-xLif57pHpDyX0yLYV_SsOLf0LiipTS7/view?usp=drive_link",
		"10" : "Lakukanlah Lompat Crazy Frog,https://drive.google.com/file/d/105j3G3S7NbGYCK-IXUDAhqo4tysOXGhW/view?usp=drive_link",
		"11" : "Lakukanlah Loncat Marsupilami,https://drive.google.com/file/d/14HcSVQu6aVgATKy3nVl17BHeHphjAb7L/view?usp=drive_link",
		"12" : "Lakukanlah Jalan Tuan Crab 2 kali pengulangan,https://drive.google.com/file/d/13XoZm7nOWDCNWRoQssp2DSK_4_5P9-AX/view?usp=drive_link",
		"14" : "Lakukanlah Lari Son Go Han 2 kali pengulangan,https://drive.google.com/file/d/10-dUOETbsSt5mc3vc2F9dnwW3yXTmsL8/view?usp=drive_link", 
		"15" : "Lakukanlah Lompat Ninja Hatori,https://drive.google.com/file/d/13yjWf8cZXrbt4C8XWLHRKCOzVZUujRet/view?usp=drive_link",
		"17" : "Lakukanlah Loncat Shincan,https://drive.google.com/file/d/14Kw37WbXHwyuD41yFtLF7cN0oa_vG-KY/view?usp=drive_link", 
		"19" : "Lakukanlah Loncat Marsupilami,https://drive.google.com/file/d/14HcSVQu6aVgATKy3nVl17BHeHphjAb7L/view?usp=drive_link", 
		"20" : "Lakukanlah jalan Oscar Menekan Tombol 2 kali pengulangan,https://drive.google.com/file/d/13VME8R-nDBEAk-IFOVZjOyAJXztVYZHD/view?usp=drive_link", 
		"21" : "Lakukanlah Lari Swepper 2 kali pengulangan,https://drive.google.com/file/d/1048ayR5Co_WtnqIqLnZJsy3rxDXBb83Z/view?usp=drive_link", 
		"22" : "Lakukanlah Lompat Ultraman,https://drive.google.com/file/d/14ClO4yI84JRCVyhNwH3LlepzEEpiKbeT/view?usp=drive_link",
		"23" : "Lakukanlah Loncat Donald Duck,https://drive.google.com/file/d/14Kg1uG-Yt5ZGOG_ikvcQC4i5JuoMsx2E/view?usp=drive_link",
	},
	"gajah" : {
		"1" : "Lakukanlah Lari Ala Naruto 2 kali pengulangan,https://drive.google.com/file/d/13unWOFHy2pmF7GkkPcsXsc-pdJlwsLPx/view?usp=drive_link",
		"2" : "Lakukanlah Jalan Nobita 2 kali pengulangan,https://drive.google.com/file/d/13jdrGEfrrTuzwN5LXVMKYe6V2jYbm4_o/view?usp=drive_link",
		"4" : "Lakukanlah Lompat Boots,https://drive.google.com/file/d/104nyRlJpKxHywfQNkbYewWaclVYvIWPj/view?usp=drive_link",
		"6" : "Lakukanlah Loncat Red Kangoroo,https://drive.google.com/file/d/14EBlKp6B60ao2U3RIyWy8BDCWlju93ZT/view?usp=drive_link",
		"7" : "Lakukanlah Jalan Hulk 2 kali pengulangan,https://drive.google.com/file/d/13Y0xiJYs4GFwzwc47WaDTAkIVThj68eS/view?usp=drive_link",
		"9" : "Lakukanlah Lari Captain Tsubatsa 2 kali pengulangan,https://drive.google.com/file/d/1-xLif57pHpDyX0yLYV_SsOLf0LiipTS7/view?usp=drive_link",
		"10" : "Lakukanlah Lompat Crazy Frog,https://drive.google.com/file/d/105j3G3S7NbGYCK-IXUDAhqo4tysOXGhW/view?usp=drive_link",
		"13" : "Lakukanlah Loncat Marsupilami,https://drive.google.com/file/d/14HcSVQu6aVgATKy3nVl17BHeHphjAb7L/view?usp=drive_link",
		"14" : "Lakukanlah Jalan Tuan Crab 2 kali pengulangan,https://drive.google.com/file/d/13XoZm7nOWDCNWRoQssp2DSK_4_5P9-AX/view?usp=drive_link",
		"15" : "Lakukanlah Lari Son Go Han 2 kali pengulangan,https://drive.google.com/file/d/10-dUOETbsSt5mc3vc2F9dnwW3yXTmsL8/view?usp=drive_link", 
		"19" : "Lakukanlah Loncat Shincan,https://drive.google.com/file/d/14Kw37WbXHwyuD41yFtLF7cN0oa_vG-KY/view?usp=drive_link", 
		"20" : "Lakukanlah jalan Oscar Menekan Tombol 2 kali pengulangan,https://drive.google.com/file/d/13VME8R-nDBEAk-IFOVZjOyAJXztVYZHD/view?usp=drive_link", 
		"21" : "Lakukanlah Lari Swepper 2 kali pengulangan,https://drive.google.com/file/d/1048ayR5Co_WtnqIqLnZJsy3rxDXBb83Z/view?usp=drive_link", 
		"23" : "Lakukanlah Lompat Ultraman,https://drive.google.com/file/d/14ClO4yI84JRCVyhNwH3LlepzEEpiKbeT/view?usp=drive_link",
		"24" : "Lakukanlah Loncat Donald Duck,https://drive.google.com/file/d/14Kg1uG-Yt5ZGOG_ikvcQC4i5JuoMsx2E/view?usp=drive_link",
	},
	"kerbau" : {
		"1" : "Lakukanlah Jalan Tuan Crab 2 kali pengulangan,https://drive.google.com/file/d/13XoZm7nOWDCNWRoQssp2DSK_4_5P9-AX/view?usp=drive_link",	
		"2" : "Lakukanlah jalan Oscar Menekan Tombol 2 kali pengulangan,https://drive.google.com/file/d/13VME8R-nDBEAk-IFOVZjOyAJXztVYZHD/view?usp=drive_link", 	
		"3" : "Lakukanlah Lari Ala Naruto 2 kali pengulangan,https://drive.google.com/file/d/13unWOFHy2pmF7GkkPcsXsc-pdJlwsLPx/view?usp=drive_link",
		"5" : "Lakukanlah Jalan Nobita 2 kali pengulangan,https://drive.google.com/file/d/13jdrGEfrrTuzwN5LXVMKYe6V2jYbm4_o/view?usp=drive_link",
		"7" : "Lakukanlah Lari Captain Tsubatsa sebanyak 2 kali pengulangan,https://drive.google.com/file/d/1-xLif57pHpDyX0yLYV_SsOLf0LiipTS7/view?usp=drive_link",
		"8" : "Lakukanlah Lari Son Go Han 2 kali pengulangan,https://drive.google.com/file/d/10-dUOETbsSt5mc3vc2F9dnwW3yXTmsL8/view?usp=drive_link", 
		"9" : "Lakukanlah Lari Swepper 2 kali pengulangan,https://drive.google.com/file/d/1048ayR5Co_WtnqIqLnZJsy3rxDXBb83Z/view?usp=drive_link", 
		"10" : "Lakukanlah Lompat Ninja Hatori,https://drive.google.com/file/d/13yjWf8cZXrbt4C8XWLHRKCOzVZUujRet/view?usp=drive_link", 
		"12" : "Lakukanlah Jalan Hulk 2 kali pengulangan,https://drive.google.com/file/d/13Y0xiJYs4GFwzwc47WaDTAkIVThj68eS/view?usp=drive_link",
		"15" : "Lakukanlah Lompat Boots,https://drive.google.com/file/d/104nyRlJpKxHywfQNkbYewWaclVYvIWPj/view?usp=drive_link",
		"18" : "Lakukanlah Lompat Ultraman,https://drive.google.com/file/d/14ClO4yI84JRCVyhNwH3LlepzEEpiKbeT/view?usp=drive_link",
		"19" : "Lakukanlah Loncat Marsupilami,https://drive.google.com/file/d/14HcSVQu6aVgATKy3nVl17BHeHphjAb7L/view?usp=drive_link",
		"20" : "Lakukanlah Loncat Red Kangoroo,https://drive.google.com/file/d/14EBlKp6B60ao2U3RIyWy8BDCWlju93ZT/view?usp=drive_link",
		"21" : "Lakukanlah Loncat Donald Duck,https://drive.google.com/file/d/14Kg1uG-Yt5ZGOG_ikvcQC4i5JuoMsx2E/view?usp=drive_link",
		"22" : "Lakukanlah Loncat Marsupilami,https://drive.google.com/file/d/14HcSVQu6aVgATKy3nVl17BHeHphjAb7L/view?usp=drive_link",
		"23" : "Lakukanlah Loncat Shincan,https://drive.google.com/file/d/14Kw37WbXHwyuD41yFtLF7cN0oa_vG-KY/view?usp=drive_link", 
		"24" : "Lakukanlah Lompat Crazy Frog,https://drive.google.com/file/d/105j3G3S7NbGYCK-IXUDAhqo4tysOXGhW/view?usp=drive_link",


	},
}
