let misi = {
	"macan" : {
		"1" : "Lakukanlah Jalan Nobita 2 kali pengulangan,./video/JalanNobita.mp4",
		"3" : "Lakukanlah Lari Ala Naruto 2 kali pengulangan,./video/LariNaruto.mp4",
		"5" : "Lakukanlah Lompat Boots,./video/LompatBoots.mp4",
		"6" : "Lakukanlah Loncat Red Kangoroo,./video/LoncatRedKangoroo.mp4",
		"7" : "Lakukanlah Jalan Hulk 2 kali pengulangan,./video/JalanHulk.mp4",
		"8" : "Lakukanlah Lari Captain Tsubatsa 2 kali pengulangan,./video/LariCaptainSubatsa.mp4",
		"10" : "Lakukanlah Lompat Crazy Frog,./video/LompatCrazyFrog.mp4",
		"12" : "Lakukanlah Jalan Tuan Crab 2 kali pengulangan,./video/JalanTuanCrab.mp4",
		"13" : "Lakukanlah Loncat Marsupilami,./video/LoncatMarsupilami.mp4", //
		"15" : "Lakukanlah Lari Swepper 2 kali pengulangan,./video/LariSweeper.mp4", 
		"17" : "Lakukanlah Lompat Ninja Hatori,./video/LompatNinjaHatori.mp4", 
		"19" : "Lakukanlah Loncat Shincan,./video/LoncatSinchan.mp4", 
		"20" : "Lakukanlah jalan Oscar Menekan Tombol 2 kali pengulangan,./video/JalanOscarMenekanTombol.mp4", 
		"21" : "Lakukanlah Lari Son Go Han 2 kali pengulangan,./video/LariSonGoHan.mp4", 
		"23" : "Lakukanlah Lompat Ultraman,./video/LompatUltraman.mp4", 
		"24" : "Lakukanlah Loncat Donald Duck,./video/LoncatDonaldBebek.mp4", 
	},
	"bebek" : {
		"2" : "Lakukanlah Jalan Nobita 2 kali pengulangan,./video/JalanNobita.mp4",
		"3" : "Lakukanlah Lari Ala Naruto 2 kali pengulangan,./video/LariNaruto.mp4",
		"5" : "Lakukanlah Lompat Boots,./video/LompatBoots.mp4",
		"6" : "Lakukanlah Loncat Red Kangoroo,./video/LoncatRedKangoroo.mp4",
		"7" : "Lakukanlah Jalan Hulk 2 kali pengulangan,./video/JalanHulk.mp4",
		"8" : "Lakukanlah Lari Captain Tsubatsa 2 kali pengulangan,./video/LariCaptainSubatsa.mp4",
		"10" : "Lakukanlah Lompat Crazy Frog,./video/LompatCrazyFrog.mp4",
		"11" : "Lakukanlah Loncat Marsupilami,./video/LoncatMarsupilami.mp4",
		"12" : "Lakukanlah Jalan Tuan Crab 2 kali pengulangan,./video/JalanTuanCrab.mp4",
		"14" : "Lakukanlah Lari Son Go Han 2 kali pengulangan,./video/LariSonGoHan.mp4", 
		"15" : "Lakukanlah Lompat Ninja Hatori,./video/LompatNinjaHatori.mp4",
		"17" : "Lakukanlah Loncat Shincan,./video/LoncatSinchan.mp4", 
		"19" : "Lakukanlah Loncat Marsupilami,./video/LoncatMarsupilami.mp4", 
		"20" : "Lakukanlah jalan Oscar Menekan Tombol 2 kali pengulangan,./video/JalanOscarMenekanTombol.mp4", 
		"21" : "Lakukanlah Lari Swepper 2 kali pengulangan,./video/LariSweeper.mp4", 
		"22" : "Lakukanlah Lompat Ultraman,./video/LompatUltraman.mp4",
		"23" : "Lakukanlah Loncat Donald Duck,./video/LoncatDonaldBebek.mp4",
	},
	"gajah" : {
		"1" : "Lakukanlah Lari Ala Naruto 2 kali pengulangan,./video/LariNaruto.mp4",
		"2" : "Lakukanlah Jalan Nobita 2 kali pengulangan,./video/JalanNobita.mp4",
		"4" : "Lakukanlah Lompat Boots,./video/LompatBoots.mp4",
		"6" : "Lakukanlah Loncat Red Kangoroo,./video/LoncatRedKangoroo.mp4",
		"7" : "Lakukanlah Jalan Hulk 2 kali pengulangan,./video/JalanHulk.mp4",
		"9" : "Lakukanlah Lari Captain Tsubatsa 2 kali pengulangan,./video/LariCaptainSubatsa.mp4",
		"10" : "Lakukanlah Lompat Crazy Frog,./video/LompatCrazyFrog.mp4",
		"13" : "Lakukanlah Loncat Marsupilami,./video/LoncatMarsupilami.mp4",
		"14" : "Lakukanlah Jalan Tuan Crab 2 kali pengulangan,./video/JalanTuanCrab.mp4",
		"15" : "Lakukanlah Lari Son Go Han 2 kali pengulangan,./video/LariSonGoHan.mp4", 
		"19" : "Lakukanlah Loncat Shincan,./video/LoncatSinchan.mp4", 
		"20" : "Lakukanlah jalan Oscar Menekan Tombol 2 kali pengulangan,./video/JalanOscarMenekanTombol.mp4", 
		"21" : "Lakukanlah Lari Swepper 2 kali pengulangan,./video/LariSweeper.mp4", 
		"23" : "Lakukanlah Lompat Ultraman,./video/LompatUltraman.mp4",
		"24" : "Lakukanlah Loncat Donald Duck,./video/LoncatDonaldBebek.mp4",
	},
	"kerbau" : {
		"1" : "Lakukanlah Jalan Tuan Crab 2 kali pengulangan,./video/JalanTuanCrab.mp4",	
		"2" : "Lakukanlah jalan Oscar Menekan Tombol 2 kali pengulangan,./video/JalanOscarMenekanTombol.mp4", 	
		"3" : "Lakukanlah Lari Ala Naruto 2 kali pengulangan,./video/LariNaruto.mp4",
		"5" : "Lakukanlah Jalan Nobita 2 kali pengulangan,./video/JalanNobita.mp4",
		"7" : "Lakukanlah Lari Captain Tsubatsa sebanyak 2 kali pengulangan,./video/LariCaptainSubatsa.mp4",
		"8" : "Lakukanlah Lari Son Go Han 2 kali pengulangan,./video/LariSonGoHan.mp4", 
		"9" : "Lakukanlah Lari Swepper 2 kali pengulangan,./video/LariSweeper.mp4", 
		"10" : "Lakukanlah Lompat Ninja Hatori,./video/LompatNinjaHatori.mp4", 
		"12" : "Lakukanlah Jalan Hulk 2 kali pengulangan,./video/JalanHulk.mp4",
		"15" : "Lakukanlah Lompat Boots,./video/LompatBoots.mp4",
		"18" : "Lakukanlah Lompat Ultraman,./video/LompatUltraman.mp4",
		"19" : "Lakukanlah Loncat Marsupilami,./video/LoncatMarsupilami.mp4",
		"20" : "Lakukanlah Loncat Red Kangoroo,./video/LoncatRedKangoroo.mp4",
		"21" : "Lakukanlah Loncat Donald Duck,./video/LoncatDonaldBebek.mp4",
		"22" : "Lakukanlah Loncat Marsupilami,./video/LoncatMarsupilami.mp4",
		"23" : "Lakukanlah Loncat Shincan,./video/LoncatSinchan.mp4", 
		"24" : "Lakukanlah Lompat Crazy Frog,./video/LompatCrazyFrog.mp4",


	},
}
